swagger: "2.0"
info:
  description: "Foundarium test task API"
  version: "1.0.0"
  title: "Foundarium car"
  contact:
    email: "darkrino@mail.ru"
host: "localhost:8000"
basePath: "/api"
tags:
- name: "cars"
  description: "Operations about cars"
- name: "user"
  description: "Operations about user"
schemes:
- "http"
paths:
  /cars:
    get:
      tags:
      - "cars"
      summary: "Finds all cars"
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          
  /cars/{carId}:
    get:
      tags:
      - "cars"
      summary: "Get car by ID"
      operationId: "getCarById"
      produces:
      - "application/json"
      parameters:
      - name: "carId"
        in: "path"
        description: "Car to return"
        required: true
        type: "integer"
        format: "int32"
      responses:
        "200":
          description: "successful operation"
        "404":
          description: "Car not found"
  /user:
    get:
      tags:
      - "user"
      summary: "Finds all users"
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
  /user/{userId}:
    get:
      tags:
      - "user"
      summary: "Get user by ID"
      operationId: "getUserById"
      produces:
      - "application/json"
      parameters:
      - name: "userId"
        in: "path"
        description: "User to return"
        required: true
        type: "integer"
        format: "int32"
      responses:
        "200":
          description: "successful operation"
        "404":
          description: "User not found"
  /user/{userId}/getcar/{car_name}:
    get:
      tags:
      - "user"
      summary:  "Receipt by the user of the car"
      produces:
      - "application/json"
      parameters:
      - name: "userId"
        in: "path"
        required: true
        type: "integer"
      - name: "car_name"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
        "404":
          description: "car or user not found"     
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          